spring:
  application:
    name: product-microservice # Name for identification in Eureka
  cloud:
    config:
      uri: http://localhost:8888 # Config Server URL
      import: "optional:configserver:" # Optional usage of configserver
      import-check:
        enabled: false # Disable config import check to avoid errors
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server URL

management:
  endpoints:
    web:
      exposure:
        include: info, health
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans # Zipkin Server URL

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
