spring:
  application:
    name: product-microservice
  datasource:
    url: jdbc:mysql://${placeholder.db.host.product}:3306/${placeholder.db.name.product}
    username: ${placeholder.db.username}
    password: ${placeholder.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG